import { WeaponDef } from './defs';
import { DamageType } from '../types';

export const WEAPONS: WeaponDef[] = [
  {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    category: 'weapon',
    weight: 3,
    value: 5,
    damageType: DamageType.SLASH,
    baseDamage: 10,
    maxDurability: 50,
    range: 36,
    cooldown: 400,
    attackDuration: 150,
    noiseRadius: 4,
  },
  {
    id: 'wooden_club',
    name: 'Wooden Club',
    category: 'weapon',
    weight: 4,
    value: 3,
    damageType: DamageType.BLUNT,
    baseDamage: 8,
    maxDurability: 40,
    range: 30,
    cooldown: 500,
    attackDuration: 150,
    noiseRadius: 6,
  },
  {
    id: 'iron_spear',
    name: 'Iron Spear',
    category: 'weapon',
    weight: 3.5,
    value: 15,
    damageType: DamageType.THRUST,
    baseDamage: 12,
    maxDurability: 60,
    range: 48,
    cooldown: 600,
    attackDuration: 120,
    noiseRadius: 2,
  },
  {
    id: 'short_sword',
    name: 'Short Sword',
    category: 'weapon',
    weight: 2.5,
    value: 20,
    damageType: DamageType.SLASH,
    baseDamage: 14,
    maxDurability: 80,
    range: 32,
    cooldown: 350,
    attackDuration: 130,
    noiseRadius: 4,
  },
  {
    id: 'war_hammer',
    name: 'War Hammer',
    category: 'weapon',
    weight: 6,
    value: 25,
    damageType: DamageType.BLUNT,
    baseDamage: 18,
    maxDurability: 100,
    range: 28,
    cooldown: 700,
    attackDuration: 200,
    noiseRadius: 7,
  },
];
